services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      /bin/bash -c "
      ollama serve &
      sleep 2 &&
      ollama pull tinyllama &&
      tail -f /dev/null
      "

  minivault-api:
    build: .
    container_name: minivault-api
    environment:
      - MINIVAULT_LLM_SERVICE__TYPE=ollama
      - MINIVAULT_LLM_SERVICE__BASE_URL=http://ollama:11434
      - MINIVAULT_LLM_SERVICE__MODEL=tinyllama
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - ./logs:/app/logs

volumes:
  ollama_data: 